import { ICache } from "./Cache";
import { IContext } from "./Context";
import { ILogger } from "../logging/Logger";

export interface IOptions {
    sdkKey?: string;
    baseUri?: string;
    streamUri?: string;
    eventsUri?: string;
    cache?: ICache;
    context?: IContext;
    /**
     * Configures a logger for warnings and errors generated by the SDK.
     *
     * The logger can be any object that conforms to the {@link ILogger} interface.
     * For a simple implementation that lets you filter by log level, see
     * {@link BasicLogger}. You can also use an instance of `winston.Logger` from
     * the Winston logging package.
     *
     * If you do not set this property, the SDK uses {@link BasicLogger} with a
     * minimum level of `info`.
     */
    logger?: ILogger;
    /**
     * The connection timeout, in seconds.
     */
    timeout?: number;
}